[project]
name = "mountain-car-rl"
version = "0.1.0"
description = "RL Mountain Car project"
requires-python = ">=3.9"
dependencies = [
    "gymnasium",
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "tqdm",
    "ipykernel",
    "moviepy>=2.2.1",
    "pygame>=2.6.1",
]

[tool.uv]
package = false
